steps:
  - name : ZESPRI Canopy SAP BW
    cpiApiServiceKeyCredentialsId: sapcpidevServiceKeyCredentials
    integrationFlowId: GET_CRM_Data
    packageId : 'ZESPRICanopySAPBW'
    integrationFlowVersion: 1.4
    downloadPath: /var/lib/jenkins/workspace/SAPCPIArtifactDownload/IntegrationContent/ZESPRICanopySAPBW/GET_CRM_Data
