steps:
  - name : ZESPRI Canopy SAP BW
    cpiApiServiceKeyCredentialsId: sapcpidevServiceKeyCredentials
    integrationFlowId: GET_CRM_Data
    packageId : 'ZESPRICanopySAPBW'
    integrationFlowVersion: 1.0.2
    downloadPath: ./ZESPRICanopySAPBW
